# Generated by Django 5.2.8 on 2025-12-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_item", models.CharField(max_length=150)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "old_property_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Old Property No. Assigned",
                    ),
                ),
                (
                    "new_property_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="New Property No. Assigned",
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity_per_property_card",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "quantity_per_physical_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Location / Whereabouts",
                    ),
                ),
                (
                    "condition",
                    models.IntegerField(
                        choices=[
                            (0, "Serviceable"),
                            (1, "Beyond Economical Repair (BER)"),
                        ],
                        default=0,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("accounted", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "unitofmeasure",
                "verbose_name_plural": "unitofmeasures",
            },
        ),
    ]
