# Generated by Django 5.2.8 on 2025-12-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'verbose_name': 'Unit of Measure', 'verbose_name_plural': 'Unit of Measures'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Serviceable'), (2, 'Beyond Economical Repair (BER)')], default=0),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='items.inventoryitem'),
        ),
    ]
