# Generated by Django 5.2.8 on 2025-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='qr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
